### ISSUE TITLE
Server crash with 5.0 update

### ISSUE THREAD

**Issue by Loris099** [TheComputerizer/Music-Triggers#17]
Hello, after the 5.0 update I can't open my server since it just crash.
Seems like Music Triggers causes a fatal error.
I have also tested without other mods and still crash

Crash report
https://mclo.gs/KZNZp95

**Comment by TheComputerizer** [comment]
This is a known issue due to me accidentally registering some client classes on the server. A fix should be live sometime today

**Comment by Loris099** [comment]
Thank you so much for the reply, I'm loving the mod :D

Il Gio 14 Apr 2022, 20:56 TheComputerizer ***@***.***> ha
scritto:

**Comment by TheComputerizer** [comment]
This should be fixed in 5.1

**Comment by Loris099** [comment]
The server still crash in 5.1

https://mclo.gs/EvIavxR

Il Ven 15 Apr 2022, 11:47 TheComputerizer ***@***.***> ha
scritto:

**Comment by TheComputerizer** [comment]
I may have accidentally only stopped registering 1 of the 2 client classes on the server. I will fix and test it with the rest of the issues this weekend

**Comment by TheComputerizer** [comment]
This should be fixed for real this time in 5.2
