### ISSUE TITLE
[Incompatibility] Music Duration Reducer

### ISSUE THREAD

**Issue by Rad233** [TheComputerizer/Music-Triggers#50]
Game version: 1.18.1, Fabric, mod version: 5.4
The game crashed after the first song played in the game ends. Is there any imcompatibility with "Music Duration Reducer" mod or "Keep That Music" mod? 

Crash report:

Description: Unexpected error

java.lang.NullPointerException: Cannot load from object array because the return value of "java.util.Map.get(Object)" is null
	at mods.thecomputerizer.musictriggers.client.MusicPlayer.lambda$onTick$2(MusicPlayer.java:341)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
	at mods.thecomputerizer.musictriggers.client.MusicPlayer.onTick(MusicPlayer.java:341)
	at mods.thecomputerizer.musictriggers.MusicTriggersClient.lambda$setUpClientEvents$2(MusicTriggersClient.java:99)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$dha000$onEndTick(class_310.java:12997)
	at net.minecraft.class_310.method_1574(class_310.java:1807)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

musictriggers.toml

[1]
	[[1.trigger]]
		name = "light"
		level = "15"
	[[1.trigger]]
		name = "raining"
	[[1.trigger]]
		name = "generic"

[2]
	[[2.trigger]]
		name = "generic"
	[[2.trigger]]
		name = "home"

[3]
	[[3.trigger]]
		name = "biome"
		biome_category = "icy"
	[[3.trigger]]
		name = "light"
		level = "7"
	[[3.trigger]]
		name = "generic"

[4]
	[[4.trigger]]
		name = "biome"
		biome_category = "beach"
	[[4.trigger]]
		name = "biome"
		biome_category = "forest"
	[[4.trigger]]
		name = "biome"
		biome_category = "plains"
	[[4.trigger]]
		name = "elytra"
	[[4.trigger]]
		name = "biome"
		biome_category = "mountain"
	[[4.trigger]]
		name = "biome"
		biome_category = "savanna"
	[[4.trigger]]
		name = "generic"
	[[4.trigger]]
		name = "light"
		level = "15"

[5]
	[[5.trigger]]
		name = "biome"
		biome_category = "plains"
	[[5.trigger]]
		name = "biome"
		biome_category = "swamp"
	[[5.trigger]]
		name = "biome"
		biome_category = "beach"
	[[5.trigger]]
		name = "generic"
	[[5.trigger]]
		name = "biome"
		biome_category = "forest"
	[[5.trigger]]
		name = "light"
		level = "15"
	[[5.trigger]]
		name = "biome"
		biome_category = "savanna"

[6]
	[[6.trigger]]
		name = "biome"
		biome_category = "plains"
	[[6.trigger]]
		name = "biome"
		biome_category = "mountain"
	[[6.trigger]]
		name = "biome"
		biome_category = "beach"
	[[6.trigger]]
		name = "generic"
	[[6.trigger]]
		name = "biome"
		biome_category = "forest"
	[[6.trigger]]
		name = "light"
		level = "15"
	[[6.trigger]]
		name = "biome"
		biome_category = "taiga"

[7]
	[[7.trigger]]
		name = "biome"
		biome_category = "forest"
	[[7.trigger]]
		name = "time"
		start = "sunrise"
	[[7.trigger]]
		name = "biome"
		biome_category = "taiga"
	[[7.trigger]]
		name = "biome"
		biome_category = "plains"
	[[7.trigger]]
		name = "biome"
		biome_category = "extreme_hills"
	[[7.trigger]]
		name = "biome"
		biome_category = "mountain"
	[[7.trigger]]
		name = "generic"
	[[7.trigger]]
		name = "light"
		level = "15"

[8]
	[[8.trigger]]
		name = "generic"
	[[8.trigger]]
		name = "biome"
		rain_type = "snow"

[9]
	[[9.trigger]]
		name = "generic"
	[[9.trigger]]
		name = "riding"
		time = "400"
	[[9.trigger]]
		name = "time"
		start = "sunrise"
	[[9.trigger]]
		name = "biome"
		biome_category = "mountain"
	[[9.trigger]]
		name = "biome"
		biome_category = "extreme_hills"
	[[9.trigger]]
		name = "elytra"
		start = "200"

[10]
	[[10.trigger]]
		name = "time"
		start = "sunset"
	[[10.trigger]]
		name = "home"
	[[10.trigger]]
		name = "generic"

[11]
	[[11.trigger]]
		name = "generic"
	[[11.trigger]]
		name = "underwater"
	[[11.trigger]]
		name = "fishing"
	[[11.trigger]]
		name = "biome"
		biome_category = "ocean"

[12]
	[[12.trigger]]
		name = "time"
		time = "night"
	[[12.trigger]]
		name = "generic"
	[[12.trigger]]
		name = "dead"
	[[12.trigger]]
		name = "snowing"
	[[12.trigger]]
		name = "storming"

[13]
	[[13.trigger]]
		name = "generic"
	[[13.trigger]]
		name = "time"
		time = "day"
	[[13.trigger]]
		name = "snowing"
	[[13.trigger]]
		name = "riding"

[14]
	[[14.trigger]]
		name = "biome"
		biome_category = "forest"
	[[14.trigger]]
		name = "time"
		start = "sunrise"
	[[14.trigger]]
		name = "biome"
		biome_category = "taiga"
	[[14.trigger]]
		name = "biome"
		biome_category = "plains"
	[[14.trigger]]
		name = "biome"
		biome_category = "extreme_hills"
	[[14.trigger]]
		name = "biome"
		biome_category = "mountain"
	[[14.trigger]]
		name = "generic"
	[[14.trigger]]
		name = "light"
		level = "15"

[15]
	[[15.trigger]]
		name = "biome"
		biome_category = "taiga"
	[[15.trigger]]
		name = "generic"
	[[15.trigger]]
		name = "biome"
		biome_category = "extreme_hills"
	[[15.trigger]]
		name = "underwater"
	[[15.trigger]]
		name = "snowing"
	[[15.trigger]]
		name = "light"
		level = "15"
	[[15.trigger]]
		name = "biome"
		biome_category = "mountain"
	[[15.trigger]]
		name = "riding"
	[[15.trigger]]
		name = "biome"
		biome_category = "forest"

[16]
	[[16.trigger]]
		name = "biome"
		biome_category = "plains"
	[[16.trigger]]
		name = "biome"
		biome_category = "swamp"
	[[16.trigger]]
		name = "biome"
		biome_category = "beach"
	[[16.trigger]]
		name = "generic"
	[[16.trigger]]
		name = "biome"
		biome_category = "forest"
	[[16.trigger]]
		name = "light"
		level = "15"
	[[16.trigger]]
		name = "biome"
		biome_category = "savanna"

[17]
	[[17.trigger]]
		name = "biome"
		biome_category = "river"
	[[17.trigger]]
		name = "biome"
		biome_category = "forest"
	[[17.trigger]]
		name = "underwater"
	[[17.trigger]]
		name = "generic"
	[[17.trigger]]
		name = "home"
	[[17.trigger]]
		name = "biome"
		biome_category = "icy"
	[[17.trigger]]
		name = "biome"
		biome_category = "mountain"

[18]
	[[18.trigger]]
		name = "dead"
	[[18.trigger]]
		name = "generic"
	[[18.trigger]]
		name = "home"
	[[18.trigger]]
		name = "light"
		level = "15"
	[[18.trigger]]
		name = "raining"

[19]
	[[19.trigger]]
		name = "time"
		start = "night"
	[[19.trigger]]
		name = "generic"
	[[19.trigger]]
		name = "home"
	[[19.trigger]]
		name = "dead"
	[[19.trigger]]
		name = "raining"

[20]
	[[20.trigger]]
		name = "dead"
	[[20.trigger]]
		name = "storming"
	[[20.trigger]]
		name = "elytra"
	[[20.trigger]]
		name = "generic"
	[[20.trigger]]
		name = "biome"
		biome_category = "underground"
	[[20.trigger]]
		name = "time"
		start = "night"
	[[20.trigger]]
		name = "raining"

[21]
	[[21.trigger]]
		name = "generic"
	[[21.trigger]]
		name = "time"
		start = "night"
	[[21.trigger]]
		name = "biome"
		biome_category = "underground"
	[[21.trigger]]
		name = "mob"
		resource_name = "MOB"
		mob_targeting = "true"
		victory = "true"

[22]
	[[22.trigger]]
		name = "time"
		start = "sunrise"
	[[22.trigger]]
		name = "riding"
	[[22.trigger]]
		name = "generic"

Full file:
[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/8725194/latest.log)
[crash-2022-05-19_12.54.59-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/8725200/crash-2022-05-19_12.54.59-
[musictriggers.toml.txt](https://github.com/TheComputerizer/Music-Triggers/files/8725275/musictriggers.toml.txt)
client.txt)

**Comment by TheComputerizer** [comment]
Music Duration Reducer is a known incompatibility, not sure about the other one. I will leave this open for now since this type of issue should be fixed in the rework for 6.0

**Comment by Rad233** [comment]
> Music Duration Reducer is a known incompatibility, not sure about the other one. I will leave this open for now since this type of issue should be fixed in the rework for 6.0
I removed these two mods, but the crash(with the same crash report content) still occured...

**Comment by TheComputerizer** [comment]
Are you sure all the songs in your config match the names of files in your music folder?

**Comment by Rad233** [comment]
> Are you sure all the songs in your config match the names of files in your music folder?
Yeah,sure. I just named them with numbers.

**Comment by TheComputerizer** [comment]
This should no longer be an issue in 6.0
